sudo: required
services:
  - docker

before_install:
  - dokcer build -t rhs99/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run rhs99/react-test npm test -- --coverage

after_success:
  - docker build -t rhs99/multi-client ./client
  - docker build -t rhs99/multi-nginx ./nginx
  - docker build -t rhs99/multi-server ./server
  - docker build -t rhs99/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rhs99/multi-client 
  - docker push rhs99/multi-nginx 
  - docker push rhs99/multi-server 
  - docker push rhs99/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-multi-container"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-306476627547"
  bucket_path: "docker-multi-container"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY