version: 2.1
jobs:
  test:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t multi-client-dev ./client
      - run:
          name: Run Tests
          command: |
            docker run --rm -t multi-client-dev npm run test
workflows:
  example:
    jobs:
      - test