version: 2.1
jobs:
  test:
    docker:
      - image: docker:latest

    working_directory: /app

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t rhs99/react-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Run Tests
          command: |
            docker run rhs99/react-test npm test -- --coverage
workflows:
  example:
    jobs:
      - test